; Runtime PHP (dipakai dev & production)
memory_limit = 256M
upload_max_filesize = 100M
; Harus >= upload_max_filesize
post_max_size = 100M
max_execution_time = 300
; Sesuaikan zona waktu aplikasi, mis. Asia/Jakarta
date.timezone = UTC
display_errors = Off
log_errors = On
expose_php = Off
